### PR TITLE
Add translation for Authors folder

### LINKED ISSUE #50: Translate id and Title of "Authors" folderish
Create the "Authors" folder based on the translated id and Title for the given language

### PR DESCRIPTION
**Pull request by jonaspiterek**
# ToDo
 - [x] Add tests
 - [x] Fix id not being translated

Fix #50

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
@jonaspiterek Have you actually tested this with a different language? I don't think it will work.

Message id objects created with the `_` helper are automatically translated into the current language in certain places -- such as when they appear in a template or are serialized to JSON for an API response. But, I don't think `api.content.create` will take care of translating them. So, I expect that we need to do it manually before passing the translated values into `api.content.create`.

Here's an example of how to do it manually: https://github.com/plone/plone.restapi/blob/d5b83a67b5a894b7985c67e6c2ae0c9eb1034fd6/src/plone/restapi/services/users/add.py#L40

**Comment by jonaspiterek** [comment]
@davisagli I did tested it with a different language and it is kind of working, "title" and "description" get the translation. But "id" does not. Also the breadcrumbs which I believe use the "title" don't work.

**Comment by ericof** [comment]
Additional code added here to handle the https://github.com/plone/plone.api/issues/524 issue

**Review by jonaspiterek — COMMENTED** [review]
@ericof Works exactly as expected

**Review by ericof — APPROVED** [review]

**Pull request merged**
